import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" className={`${inter.variable} ${roboto_mono.variable}}`}>
        <body className="font-mono bg-gradient-to-b from-[#2B1810] to-[#1a0f0a]">
          {children}
          <ToastContainer />
        </body>
      </html>
    </AuthProvider>
  );
}
